#pragma once

#define STOP_SENDING_STREAM_COMMAND_TYPE 0x7F
#define STREAM_COMMAND_RESPONSE_CODE 128

enum UartRpcError{
    //common
    UART_RPC_CRC_MISMATCH,
    UART_RPC_FRAMING_ERROR,

    //client
    UART_RPC_TIMEOUT,
    UART_RPC_MISSING_PACKET_IN_STREAM,
    UART_RPC_UNSOLICITED_MESSAGE,
};
